// Umbrella header for NougatUI.
#import "CADisplayLink+Blocks.h"
#import "NSArray+Map.h"
#import "NUABatteryView.h"
#import "NUABrightnessModuleController.h"
#import "NUAFlipswitchToggle.h"
#import "NUAModulesContainerViewController.h"
#import "NUANotificationCenterInhibitor.h"
#import "NUANotificationShadeContainerView.h"
#import "NUANotificationShadeController.h"
#import "NUANotificationShadeModuleViewController.h"
#import "NUANotificationShadePageContainerViewController.h"
#import "NUANotificationShadePageContentProvider.h"
#import "NUANotificationShadePanelView.h"
#import "NUANotificationShadeViewController.h"
#import "NUARippleButton.h"
#import "NUARippleLayer.h"
#import "NUASettingsContentView.h"
#import "NUASettingsModuleController.h"
#import "NUAStatusBarContentView.h"
#import "NUAStatusBarModuleController.h"
#import "NUATogglesContentView.h"
#import "NUATogglesModuleController.h"

