include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = NightLightToggle
NightLightToggle_BUNDLE_NAME = com.shade.nougat.NightLightToggle
NightLightToggle_BUNDLE_EXTENSION = bundle
NightLightToggle_FILES = $(wildcard *.m)
NightLightToggle_FRAMEWORKS = Foundation UIKit CoreGraphics CoreImage QuartzCore
NightLightToggle_EXTRA_FRAMEWORKS = NougatUI
NightLightToggle_INSTALL_PATH = /Library/Nougat/Toggles/

include $(THEOS_MAKE_PATH)/bundle.mk