#import <UIKit/UIKit.h>

@protocol BSInvalidatable, CSExternalBehaviorProviding;
@class SBTransientOverlayPresentationManager, UIApplicationSceneDeactivationAssertion;

@protocol SBTransientOverlayPresentationManagerDelegate <NSObject>

@required

- (void)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager didDismissViewController:(UIViewController *)viewController wasTopmostPresentation:(BOOL)wasTopmostPresentation;
- (void)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager willPresentViewController:(UIViewController *)viewController;
- (void)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager preferredWhitePointAdaptivityStyleDidChangeWithAnimationSettings:(id)animationSettings;
- (BOOL)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager shouldResignFirstResponderForKeyWindow:(UIWindow *)keyWindow;
- (BOOL)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager shouldRestoreFirstResponderForKeyWindow:(UIWindow *)keyWindow;
- (void)transientOverlayPresentationManagerRequestsAppIconForceTouchDismissal:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager animated:(BOOL)animated;
- (id<BSInvalidatable>)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager acquireWallpaperAnimationSuspensionAssertionWithReason:(NSString *)reason;
- (id<BSInvalidatable>)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager acquireDisableAutoUnlockAssertionWithReason:(NSString *)reason;
- (id<BSInvalidatable>)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager acquireProximitySensorEnabledAssertionWithReason:(NSString *)reason;
- (id<BSInvalidatable>)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager acquireInteractiveScreenshotGestureDisabledAssertionWithReason:(NSString *)reason;
- (id)bannerLongLookPresentationObservationTokenForTransientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager;
- (id<BSInvalidatable>)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager acquireBannerLongLookWindowLevelAssertionWithReason:(NSString *)reason windowLevel:(UIWindowLevel)windowLevel;
- (void)transientOverlayPresentationManagerRequestsBannerLongLookDismissal:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager animated:(BOOL)animated;
- (id)controlCenterPresentationObservationTokenForTransientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager;
- (id<BSInvalidatable>)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager acquireControlCenterWindowLevelAssertionWithReason:(NSString *)reason windowLevel:(UIWindowLevel)windowLevel;
- (void)transientOverlayPresentationManagerRequestsControlCenterDismissal:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager animated:(BOOL)animated;
- (id)siriPresentationObservationTokenForTransientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager;
- (id<BSInvalidatable>)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager acquireSiriWindowLevelAssertionWithReason:(NSString *)reason windowLevel:(UIWindowLevel)windowLevel;
- (void)transientOverlayPresentationManagerRequestsSiriDismissal:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager animated:(BOOL)animated;
- (id)currentStatusBarSettingsForTransientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager;
- (id<BSInvalidatable>)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager acquireHideAppStatusBarAssertionWithReason:(NSString *)reason;
- (id<BSInvalidatable>)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager acquireDeviceOrientationUpdateDeferralAssertionWithReason:(NSString *)reason;
- (UIApplicationSceneDeactivationAssertion *)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager newSceneDeactivationAssertionWithReason:(NSInteger)reason;
- (void)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager registerCoverSheetExternalBehaviorProvider:(id<CSExternalBehaviorProviding>)externalBehaviorProvider;
- (void)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager unregisterCoverSheetExternalBehaviorProvider:(id<CSExternalBehaviorProviding>)xternalBehaviorProvider;
- (void)transientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager willChangeTopmostViewControllerInterfaceOrientationToOrientation:(UIInterfaceOrientation)orientation;
- (UIInterfaceOrientation)defaultSupportedInterfaceOrientationsForTransientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager;
- (UIInterfaceOrientation)defaultPreferredInterfaceOrientationForPresentationForTransientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager;
- (BOOL)defaultShouldAutorotateForTransientOverlayPresentationManager:(SBTransientOverlayPresentationManager *)transientOverlayPresentationManager;

@end