include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = BluetoothToggle
BluetoothToggle_BUNDLE_NAME = com.shade.nougat.BluetoothToggle
BluetoothToggle_BUNDLE_EXTENSION = bundle
BluetoothToggle_FILES = $(wildcard *.m)
BluetoothToggle_FRAMEWORKS = Foundation UIKit CoreGraphics CoreImage QuartzCore
BluetoothToggle_EXTRA_FRAMEWORKS = NougatUI
BluetoothToggle_INSTALL_PATH = /Library/Nougat/Toggles/

include $(THEOS_MAKE_PATH)/bundle.mk