include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = RotationLockToggle
RotationLockToggle_BUNDLE_NAME = com.shade.nougat.RotationLockToggle
RotationLockToggle_BUNDLE_EXTENSION = bundle
RotationLockToggle_FILES = $(wildcard *.m)
RotationLockToggle_FRAMEWORKS = Foundation UIKit CoreGraphics CoreImage QuartzCore
RotationLockToggle_EXTRA_FRAMEWORKS = NougatUI
RotationLockToggle_INSTALL_PATH = /Library/Nougat/Toggles/

include $(THEOS_MAKE_PATH)/bundle.mk