include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = DarkThemeToggle
DarkThemeToggle_BUNDLE_NAME = com.shade.nougat.DarkThemeToggle
DarkThemeToggle_BUNDLE_EXTENSION = bundle
DarkThemeToggle_FILES = $(wildcard *.m)
DarkThemeToggle_FRAMEWORKS = Foundation UIKit CoreGraphics CoreImage QuartzCore
DarkThemeToggle_EXTRA_FRAMEWORKS = NougatUI
DarkThemeToggle_INSTALL_PATH = /Library/Nougat/Toggles/

include $(THEOS_MAKE_PATH)/bundle.mk