include $(THEOS)/makefiles/common.mk

export ADDITIONAL_CFLAGS += -I../../Headers

SUBPROJECTS += AirplaneModeToggle
SUBPROJECTS += BatterySaverToggle
SUBPROJECTS += BluetoothToggle
SUBPROJECTS += DataToggle
SUBPROJECTS += DoNotDisturbToggle
SUBPROJECTS += FlashlightToggle
SUBPROJECTS += LocationToggle
SUBPROJECTS += RotationLockToggle
SUBPROJECTS += WiFiToggle

include $(THEOS_MAKE_PATH)/aggregate.mk